-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Mirrors announcement_requests.is_security_announcement (the pre-publish
-- draft/approval side, added in 000077) onto the published side. The two
-- tables were built ~4 months apart by unrelated work and were never
-- reconciled, so the published announcement row has had no way to say
-- whether it's a security announcement -- the ServiceNow-side visibility
-- ACLs gate on exactly this distinction (current.u_announcement_type == 2),
-- and any Postgres-side reimplementation of that visibility rule needs the
-- same signal here.
--
-- Defaults to false (general) rather than true: there is currently no
-- write path in this service that sets announcement.* at all (rows arrive
-- via an external ServiceNow sync, not through entity-service), so every
-- existing row is a historical row of unknown classification. Defaulting
-- to false is the safer choice for that unknown population -- it keeps
-- existing general announcements visible to the audience that already
-- reads them, at the cost of also under-classifying any historical
-- security announcement as general until backfilled from ServiceNow's own
-- u_announcement_type. That backfill, and wiring the sync job to populate
-- this column for new rows going forward, are both separate follow-ups --
-- out of scope for this migration, which only adds the column.
ALTER TABLE announcement
  ADD COLUMN IF NOT EXISTS is_security_announcement BOOLEAN NOT NULL DEFAULT false;
